name: Build
description: Build php image
inputs:
  secret_github_token:
    description: github token
    required: true
  version:
    description: version
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
#        platforms: linux/amd64,linux/arm64
        platforms: linux/amd64
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Github Container registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.secret_github_token }}
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        build-args: PHP_VERSION=${{ inputs.version }}
#        platforms: linux/amd64,linux/arm64
        platforms: linux/amd64
        push: true
        tags: ghcr.io/${{ github.actor }}/php:${{ inputs.version }}